## Exercici 1

In [1]:
nota = 9

In [2]:
if nota >= 0 and nota < 5:
   print("Suspès")
elif nota >= 5 and nota < 6:
   print("Aprovat")
elif nota >= 7 and nota < 9:    
   print("Notable")
elif nota >= 9 and nota <= 10:
   print("Excel·lent")
else:
   print("Nota errònia")


Excel·lent


## Exercici 2

In [4]:
num1= input("Entrea un número: ")
num2= input("Entra un altre número: ")

Entrea un número: 7
Entra un altre número: 8


In [5]:
if num1 > num2:
 print("El primer número introduït, {}, és més gran que el segon, {}.".format(num1,num2))
elif num1 < num2:
 print("El primer número introduït, {}, és més petit que el segon, {}.".format(num1,num2))
else:
 print("Els dos números introduïts, {} i {}, són iguals.".format(num1,num2))


El primer número introduït, 7, és més petit que el segon, 8.


## Exercici 3

In [6]:
nom= input("Introdueix el teu nom, si us plau: ")
num= int(input("Ara introdueix un número, si us plau: "))
if num == 0:
 print("Número erroni, intenta-ho de nou.")
else:
 print((nom + " ") * num)


Introdueix el teu nom, si us plau: Manel
Ara introdueix un número, si us plau: 7
Manel Manel Manel Manel Manel Manel Manel 


## Exercici 4

In [7]:
import numpy as np


In [8]:
llista=([4,1,5],[7,2,6],[6,2,1])
l=np.array(llista)
print(l)


[[4 1 5]
 [7 2 6]
 [6 2 1]]


In [9]:
files=l.shape[0]
columnes=l.shape[1]
elem= files * columnes


In [10]:
if files == columnes:
 print("La llista és simètrica perquè té {} files i {} columnes, és a dir {} elements.".format(files,columnes,elem))
 
else:
 print("La llista és assimètrica.")


La llista és simètrica perquè té 3 files i 3 columnes, és a dir 9 elements.


In [11]:
print("El nombre d'elements també es pot saber amb la funció size i dóna el mateix resultat, " + str(l.size) +".")


El nombre d'elements també es pot saber amb la funció size i dóna el mateix resultat, 9.


### Exercici 5

In [13]:
llista= [3,1,5,3,4,4,6,15,9]
idx = 0
res = []


In [15]:
for i in llista:
  if i == idx:
     res.append(idx)
  idx = idx + 1
 
print("Números que coincideixen amb la seva posició:\n",res)
 


Números que coincideixen amb la seva posició:
 [1, 3, 4, 6]
